# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mk4eW0L2zaJV6YLRU00ogNeIUchZNivj
"""

import h5py
with h5py.File('trial/prediction/h5.batch1', 'r') as f:
  pred = f['pred'][()]
print ("Percentage = ",pred[0][2]*100)